version: '3.9'

services:
  backend:
    build: ./backend
    env_file:
      - .env
    container_name: telefon_rehberi_backend
    command: >
      sh -c "python /app/backup_db.py & uvicorn api.main:app --host 0.0.0.0 --port ${BACKEND_HOST}"
    volumes:
      - ./backend/api:/app/api
      - rehber_data:/app/data
    ports:
      - "${BACKEND_HOST}:8000"

  python-app:
    build: ./service
    env_file:
      - .env
    container_name: telefon_rehberi_service
    volumes:
      - ./service:/app
      - rehber_data:/app/data
    depends_on:
      - backend
    entrypoint: ["/wait.sh"]
    command: ["python", "app.py"]

  frontend:
    build: ./frontend
    env_file:
      - .env
    container_name: telefon_rehberi_frontend
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/usr/src/app/src
    ports:
      - "${FRONTEND_HOST}:80"
    environment:
      NGINX_HOST: ${NGINX_HOST}
      NGINX_PORT: ${NGINX_PORT}
      NGINX_LISTEN: ${NGINX_LISTEN}
      NGINX_SERVER_NAME: ${NGINX_SERVER_NAME}
    depends_on:
      - backend

volumes:
  rehber_data:

