apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DEPLOYMENT_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
        - name: ${CONTAINER_NAME}
          image: ${IMAGE_NAME}:${IMAGE_VERSION}
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - "python /app/backup_db.py & uvicorn api.main:app --host 0.0.0.0 --port ${API_PORT}"
          env:
            - name: API_PORT
              value: "${API_PORT}"
            - name: SECRET
              value: "${SECRET}"
            - name: DEFAULT_ADMIN
              value: "${DEFAULT_ADMIN}"
            - name: DEFAULT_PASSWORD
              value: "${DEFAULT_PASSWORD}"
            - name: DATABASE_NAME
              value: "${DATABASE_NAME}"
            - name: DATABASE_PATH
              value: "${DATABASE_PATH}"
            - name: BACKUP_PATH
              value: "${BACKUP_PATH}"
          volumeMounts:
            - name: rehber-data
              mountPath: /app/data
      volumes:
        - name: rehber-data
          persistentVolumeClaim:
            claimName: ${PVC_NAME}
